import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './lib/supabase'
const money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})
const statusLabel={calculated:'ተቆጥሯል',finance_review:'የፋይናንስ ግምገማ',submitted:'ቀርቧል',approved:'ተፈቅዷል',paid:'ተከፍሏል',held:'ታግዷል'}
export function EarningsPage({user}){
 const [periods,setPeriods]=useState([]),[selected,setSelected]=useState(''),[rows,setRows]=useState([]),[disputes,setDisputes]=useState([]),[payments,setPayments]=useState([]),[audits,setAudits]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[action,setAction]=useState(''),[payAmount,setPayAmount]=useState(''),[payReference,setPayReference]=useState(''),[disputeReason,setDisputeReason]=useState(''),[selectedRow,setSelectedRow]=useState('')
 const global=['super_admin','admin'].includes(user.role), finance=['finance_officer','finance'].includes(user.role), canManage=global||user.role==='branch_admin'||finance
 const load=async()=>{setLoading(true);setError('');try{
  const {data:p,error:pe}=await supabase.from('commission_periods').select('*').eq('organization_id',user.organization_id).order('period_start',{ascending:false});if(pe)throw pe;setPeriods(p||[]);const active=selected||(p?.[0]?.id||'');if(!selected&&active)setSelected(active);if(!active)return
  let q=supabase.from('employee_period_earnings').select('*,profiles:employee_id(full_name,role,branch_id)').eq('commission_period_id',active)
  if(!global&&!finance)q=q.eq('employee_id',user.id);if(user.role==='branch_admin'||finance)q=q.eq('profiles.branch_id',user.branch_id)
  const {data:e,error:ee}=await q.order('net_payable',{ascending:false});if(ee)throw ee;setRows(e||[])
  const ids=(e||[]).map(x=>x.id);if(ids.length){const {data:d,error:de}=await supabase.from('disputes').select('*').in('employee_period_earnings_id',ids).order('submitted_at',{ascending:false});if(de)throw de;setDisputes(d||[]);const {data:pay,error:payErr}=await supabase.from('payments').select('*,payment_transactions(*)').in('employee_period_earnings_id',ids);if(payErr)throw payErr;setPayments(pay||[])}else{setDisputes([]);setPayments([])}
  if(global){const {data:a,error:ae}=await supabase.from('audit_logs').select('*').eq('organization_id',user.organization_id).order('created_at',{ascending:false}).limit(100);if(ae)throw ae;setAudits(a||[])}
 }catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[user.organization_id,selected,user.id,user.branch_id,user.role,global,finance])
 const totals=useMemo(()=>rows.reduce((a,r)=>({gross:a.gross+Number(r.gross_commission||0),bonuses:a.bonuses+Number(r.bonuses||0),deductions:a.deductions+Number(r.deductions||0)+Number(r.penalties||0)+Number(r.tax||0)+Number(r.legal_deductions||0),held:a.held+Number(r.amount_held||0),net:a.net+Number(r.net_payable||0)}),{gross:0,bonuses:0,deductions:0,held:0,net:0}),[rows])
 const period=periods.find(p=>p.id===selected),row=rows.find(x=>x.id===selectedRow)
 const paidFor=id=>payments.filter(p=>p.employee_period_earnings_id===id).reduce((s,p)=>s+Number(p.paid_amount||0),0)
 const call=async(a,extra={})=>{setAction(a);setError('');try{const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/functions/v1/manage-earnings',{method:'POST',headers:{Authorization:`Bearer ${session?.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:a,commission_period_id:selected,...extra})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Action failed');setPayAmount('');setPayReference('');setDisputeReason('');await load()}catch(e){setError(e.message)}finally{setAction('')}}
 return <section className="space-y-5"><div><h2 className="text-2xl font-black">የኮሚሽን እና ገቢ ማስሊያ</h2><p className="text-sm text-zinc-500">Gross Commission → Adjustments/Bonuses → Allocations/Deductions/Tax → Hold → Net Payable</p></div>
 <div className="rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><label className="block text-sm">የኮሚሽን ጊዜ<select className="input mt-1 w-full" value={selected} onChange={e=>setSelected(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.name} — {p.period_start} → {p.period_end} ({statusLabel[p.status]||p.status})</option>)}</select></label></div>
 {error&&<div className="rounded-xl bg-rose-500/10 p-3 text-rose-300">{error}</div>}{loading&&<div className="text-sm text-zinc-500">በመጫን ላይ...</div>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric t="Gross Commission" v={money(totals.gross)+' ብር'}/><Metric t="Bonus" v={money(totals.bonuses)+' ብር'}/><Metric t="Deductions/Tax" v={money(totals.deductions)+' ብር'}/><Metric t="Held" v={money(totals.held)+' ብር'}/><Metric t="Net Payable" v={money(totals.net)+' ብር'}/></div>
 <div className="rounded-2xl border bg-white dark:border-zinc-800 dark:bg-zinc-900"><div className="border-b p-4 font-bold dark:border-zinc-800">{period?.name||'የገቢ መዝገብ'}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b dark:border-zinc-800"><th className="p-3 text-left">ሰራተኛ</th><th className="p-3">Gross</th><th className="p-3">Net</th><th className="p-3">Paid</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0 dark:border-zinc-800"><td className="p-3">{r.profiles?.full_name||r.employee_id}</td><td className="p-3 text-right">{money(r.gross_commission)}</td><td className="p-3 text-right font-bold">{money(r.net_payable)} ብር</td><td className="p-3 text-right">{money(paidFor(r.id))}</td><td className="p-3 text-center">{statusLabel[r.status]||r.status}</td><td className="p-3"><button className="btn-secondary text-xs" onClick={()=>setSelectedRow(r.id)}>Manage</button></td></tr>)}</tbody></table></div></div>
 {canManage&&period&&<div className="rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="font-bold">Finance Workflow</div><div className="mt-3 flex flex-wrap gap-2"><button className="btn" disabled={!!action||period.status==='locked'} onClick={()=>call('calculate_period')}>Calculate</button>{period.status==='finance_review'&&<button className="btn" disabled={!!action} onClick={()=>call('submit_period')}>Submit</button>}{global&&<>{period.status==='submitted'&&<button className="btn" disabled={!!action} onClick={()=>call('approve_period')}>Approve Period</button>}{['submitted','approved'].includes(period.status)&&<button className="btn-secondary" disabled={!!action} onClick={()=>call('return_period',{reason:'Returned by Super Admin for correction'})}>Return</button>}{period.status==='approved'&&<button className="btn-secondary" disabled={!!action} onClick={()=>call('lock_period')}>Lock Period</button>}</>}</div>
 {row&&<div className="mt-4 rounded-xl border p-4 dark:border-zinc-800"><div className="font-bold">{row.profiles?.full_name||row.employee_id}</div><div className="mt-3 grid gap-2 sm:grid-cols-3"><input className="input" type="number" min="0" placeholder="Payment amount" value={payAmount} onChange={e=>setPayAmount(e.target.value)}/><input className="input" placeholder="Payment reference" value={payReference} onChange={e=>setPayReference(e.target.value)}/><button className="btn" disabled={!global||!payAmount||!!action||period.status!=='approved'} onClick={()=>call('record_payment',{employee_period_earnings_id:row.id,amount:Number(payAmount),payment_method:'manual',payment_reference:payReference})}>Record Payment</button></div>
 <div className="mt-3 grid gap-2 sm:grid-cols-2"><input className="input" placeholder="Dispute reason" value={disputeReason} onChange={e=>setDisputeReason(e.target.value)}/><button className="btn-secondary" disabled={!disputeReason||!!action} onClick={()=>call('submit_dispute',{employee_period_earnings_id:row.id,reason:disputeReason})}>Submit Dispute</button></div></div>}</div>}
 <div className="grid gap-5 lg:grid-cols-2"><Panel title="Disputes">{disputes.map(d=><div key={d.id} className="border-b p-3 last:border-0"><b>{d.status}</b> — {d.reason}{global&&d.status==='open'&&<div className="mt-2 flex gap-2"><input className="input" placeholder="Resolution note" id={`res-${d.id}`}/><input className="input" type="number" placeholder="Correction +/-" id={`cor-${d.id}`}/><button className="btn" onClick={()=>call('resolve_dispute',{dispute_id:d.id,resolution:'accepted',resolution_note:document.getElementById(`res-${d.id}`).value,correction_amount:Number(document.getElementById(`cor-${d.id}`).value||0)})}>Resolve</button></div>}</div>)}</Panel>{global&&<Panel title="Audit Trail">{audits.map(a=><div key={a.id} className="border-b p-3 last:border-0 text-xs"><b>{a.action}</b> · {a.entity_type} · {a.created_at}<div>{a.reason||''}</div></div>)}</Panel>}</div>
 </section>}
function Metric({t,v}){return <div className="rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="text-xs text-zinc-500">{t}</div><div className="mt-2 font-black">{v}</div></div>}
function Panel({title,children}){return <div className="rounded-2xl border bg-white dark:border-zinc-800 dark:bg-zinc-900"><div className="border-b p-4 font-bold dark:border-zinc-800">{title}</div>{children}</div>}
