import React,{useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
const today=()=>new Date().toISOString().slice(0,10)
async function act(body){const {data,error}=await supabase.functions.invoke('manage-workforce',{body});if(error)throw error;if(data?.error)throw Error(data.error);return data}
export function WorkforceManagement({currentUser}){
 const global=['super_admin','admin'].includes(currentUser.role)
 const [users,setUsers]=useState([]),[sel,setSel]=useState(null),[status,setStatus]=useState('active'),[date,setDate]=useState(today()),[reason,setReason]=useState(''),[work,setWork]=useState('working'),[att,setAtt]=useState('present'),[err,setErr]=useState('')
 const load=async()=>{let q=supabase.from('profiles').select('id,full_name,role,active,employee_status,status_effective_date,organization_id,branch_id').order('full_name');if(!global)q=q.eq('organization_id',currentUser.organization_id).eq('branch_id',currentUser.branch_id);const {data,error}=await q;if(error)throw error;setUsers(data||[])}
 useEffect(()=>{load().catch(e=>setErr(e.message))},[])
 const choose=u=>{setSel(u);setStatus(u.employee_status||'active')}
 const save=async()=>{try{await act({action:'set_employee_status',employee_id:sel.id,status,effective_date:date,reason});await load()}catch(e){setErr(e.message)}}
 const workSave=async()=>{try{await act({action:'set_daily_work_status',employee_id:sel.id,work_date:date,work_status:work,reason})}catch(e){setErr(e.message)}}
 const attSave=async()=>{try{await act({action:'record_attendance',employee_id:sel.id,work_date:date,attendance_status:att})}catch(e){setErr(e.message)}}
 return <section className="space-y-5"><h2 className="text-2xl font-black">ሰራተኛ እና Attendance</h2>{err&&<div className="rounded-xl bg-rose-500/10 p-3 text-rose-300">{err}</div>}<div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 dark:bg-zinc-900"><b>ሰራተኞች</b><div className="mt-3 space-y-2">{users.map(u=><button key={u.id} onClick={()=>choose(u)} className="w-full rounded-xl border p-3 text-left"><b>{u.full_name}</b><div className="text-xs text-zinc-500">{u.role} · {u.employee_status}</div></button>)}</div></div><div className="rounded-2xl border bg-white p-5 dark:bg-zinc-900">{sel&&<><b>{sel.full_name}</b><select className="input mt-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="fired">Fired</option><option value="resigned">Resigned</option><option value="promoted">Promoted</option><option value="suspended">Suspended</option></select><input className="input mt-3" type="date" value={date} onChange={e=>setDate(e.target.value)}/><textarea className="input mt-3" placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className="btn mt-3 w-full" onClick={save}>Status አድስ</button><hr className="my-5"/><b>የቀን የስራ ሁኔታ</b><select className="input mt-3" value={work} onChange={e=>setWork(e.target.value)}><option value="working">Working Day</option><option value="rest_day">Rest Day</option><option value="leave">Leave</option><option value="official_duty">Official Duty</option></select><button className="btn mt-3 w-full" onClick={workSave}>አስቀምጥ</button><hr className="my-5"/><b>Attendance</b><select className="input mt-3" value={att} onChange={e=>setAtt(e.target.value)}><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="leave">Leave</option><option value="sick_leave">Sick Leave</option><option value="official_duty">Official Duty</option></select><button className="btn mt-3 w-full" onClick={attSave}>Attendance መዝግብ</button></>}</div></div></section>
}